#!/bin/sh
### ### ### lxc-to-go // ### ### ###

run(){
   # execute commands inside the lxc template
   lxc-attach -n "$LXCCREATENAME" -- "$@"
}

check(){
   # check state
   if [ $? -eq 0 ]
   then
      printf "\033[1;32m OK \033[0m\n"
      sleep 2
   else
      printf "\033[1;31m FAILED \033[0m\n"
      sleep 1
      exit 1
   fi
}

lull(){
   # break
   sleep 2
   echo ""
   echo "---> next step: "$@" <---"
   echo ""
}

#/ version: 1
echo "<--- --- --- provisioning hooks // --- --- --->"

### LXC Config // ###
echo "### video & sound support // ###" >> /var/lib/lxc/"$LXCCREATENAME"/config
echo "lxc.mount.entry = /dev/dri dev/dri none bind,optional,create=dir" >> /var/lib/lxc/"$LXCCREATENAME"/config
echo "lxc.mount.entry = /dev/snd dev/snd none bind,optional,create=dir" >> /var/lib/lxc/"$LXCCREATENAME"/config
echo "lxc.mount.entry = /dev/video0 dev/video0 none bind,optional,create=file" >> /var/lib/lxc/"$LXCCREATENAME"/config
echo "#/lxc.mount.entry = /tmp/.X11-unix tmp/.X11-unix none bind,optional,create=dir" >> /var/lib/lxc/"$LXCCREATENAME"/config
echo "# WORKAROUND: against systemd-tmpfiles-clean and X clean" >> /var/lib/lxc/"$LXCCREATENAME"/config
echo "lxc.mount.entry = /tmp/.X11-unix tmp_HOST/.X11-unix none bind,optional,create=dir" >> /var/lib/lxc/"$LXCCREATENAME"/config
echo "### // video & sound support ###" >> /var/lib/lxc/"$LXCCREATENAME"/config
### // LXC Config ###

run apt-get -y update; check
run /bin/sh -c "DEBIAN_FRONTEND=noninteractive apt-get -y upgrade"; check

lull 1

# X11
run /bin/sh -c "DEBIAN_FRONTEND=noninteractive apt-get -y install xorg"; check

lull 2

/bin/cat << "RCLOCAL" > /var/lib/lxc/"$LXCCREATENAME"/rootfs/etc/rc.local
#!/bin/sh
### ### ### lxc-to-go // ### ### ###

# WORKAROUND: against systemd-tmpfiles-clean and X clean
mount --bind /tmp_HOST/.X11-unix /tmp/.X11-unix

exit 0
### ### ### // lxc-to-go ### ### ###
# EOF
RCLOCAL
check

lull 3

#/ force reboot for lxc.mount changes
#/run poweroff
printf "\033[1;33m Please Reboot your LXC Container! \033[0m\n"

echo "<--- --- --- // provisioning hooks --- --- --->"
### ### ### // lxc-to-go ### ### ###
# EOF
