#!/bin/sh
### ### ### lxc-to-go // ### ### ###

run(){
   # execute commands inside the lxc template
   lxc-attach -n "$LXCCREATENAME" -- $*
}

lull(){
   # break
   sleep 2
   echo ""
   echo "---> next step <---"
   echo ""
}

echo "<--- --- --- provisioning hooks // --- --- --->"

### EXAMPLE // ###
#

lull

run echo example

#
### // EXAMPLE ###

echo "<--- --- --- // provisioning hooks --- --- --->"
#/ exit 0
### ### ### // lxc-to-go ### ### ###
# EOF
